[package]
name = "terramach-support"
version = "0.1.0"
authors = ["Volodymyr Lykhonis <vladimirlichonos@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.9"
syn = { version = "1.0.17", features = ["full"] }
quote = "1.0.2"
